dotnet/src/Accomo.WWW/Areas/Backoffice/Controllers/KortingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Accomo.Db;
using Accomo.Models;
using Accomo.Models.Security;
using Accomo.Models.Utilities;
using Accomo.Models.ViewModels;

namespace Accomo.WWW.Areas.Backoffice.Controllers 
{
    [Area("Backoffice")]
    public class KortingController : BaseController 
    {
        public KortingController(ApplicationDbContext applicationDbContext):base(applicationDbContext)
        {
        }

        public async Task<IActionResult> Index(string sortParam) {
            List<Korting> types = 
            await ApplicationDbContext.Kortingen.ToListAsync();

            // Sorting
            ViewBag.NameSortParam = "name_asc";
            ViewBag.PercentageSortParam = "percent_asc";
            

            if(String.IsNullOrEmpty(sortParam))
            {
                types = types.OrderBy(o => o.Naam).ToList();
            }
            else
            {
                switch(sortParam)
                {
                    case "name_asc":
                        ViewBag.NameSortParam = "name_desc";
                        types = types.OrderBy(o => o.Naam).ToList();
                        break;
                    case "name_desc":
                        ViewBag.NameSortParam = "name_asc";
                        types = types.OrderByDescending(o => o.Naam).ToList();
                        break; 
                    case "percent_asc":
                        ViewBag.NameSortParam = "percent_desc";
                        types = types.OrderBy(o => o.Percentage).ToList();
                        break;
                    case "percent_desc":
                        ViewBag.NameSortParam = "percent_asc";
                        types = types.OrderByDescending(o => o.Percentage).ToList();
                        break;                    
                }
            }
            if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest") 
            {
                return PartialView("_ListPartial", types);
            }
            
            return View(types);
        }
        
        [HttpGet]
        public async Task<IActionResult> Create() 
        {  
            var viewModel = await ViewModel();
            
            return View(viewModel);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(KortingViewModel model)
        {
            var alert = new Alert();
            try
            {
                if(!ModelState.IsValid) {;
                    TempData["Status"] = ApplicationDbContextMessage.INVALID;
                    throw new Exception();
                }
                
                ApplicationDbContext.Kortingen.Add(model.Korting);
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.CREATENOK;
                    throw new Exception();
                }  
                
                TempData["Status"] = "Korting met naam: " + model.Korting.Naam + " is succesvol aangemaakt";
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;
                TempData["Status"] = ex.Message;
                
                model = await ViewModel(model.Korting);
                
                ModelState.AddModelError(string.Empty, alert.ExceptionMessage);
            }
            return View(model);
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(Int16? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            
            var model = await ApplicationDbContext.Kortingen.FirstOrDefaultAsync(m => m.Id == id);
            
            if(model == null)
            {
                return RedirectToAction("Index");
            }

            var viewModel = await ViewModel(model);
            
            return View(viewModel);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(KortingViewModel model)
        {
            var alert = new Alert();
            try 
            {
                if(!ModelState.IsValid)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.INVALID;
                    TempData["Status"] = ApplicationDbContextMessage.INVALID;
                    throw new Exception();
                }   
                    
                var originalModel = ApplicationDbContext.Kortingen.FirstOrDefault(m => m.Id == model.Korting.Id);
                
                if(originalModel == null) 
                {
                    TempData["Status"] = ApplicationDbContextMessage.NOTEXISTS;
                    throw new Exception();
                }

                originalModel.Naam = model.Korting.Naam;
                originalModel.Beschrijving = model.Korting.Beschrijving;
                originalModel.Percentage = model.Korting.Percentage;
                
                ApplicationDbContext.Attach(originalModel);
                ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {
                    TempData["Status"] = ApplicationDbContextMessage.EDITNOK;
                    throw new Exception();
                } 
                
                alert.Message = ApplicationDbContextMessage.EDITOK;
                TempData["Status"] = "Korting met Naam: " + model.Korting.Naam + " is succesvol bewerkt.";

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;
                TempData["Status"] = ex.Message;

                model = await ViewModel(model.Korting);
                ModelState.AddModelError(string.Empty, alert.ExceptionMessage);
            }
            return View(model);
        }
        
        [HttpGet("[area]/[controller]/[action]/{id:int}")]
        public async Task<IActionResult> Delete(Int16 id, [FromQuery] ActionType actionType)
        {
            var model = await ApplicationDbContext.Kortingen.FirstOrDefaultAsync(m => m.Id == id);
            if(model == null)
            {
                return RedirectToAction("Index");
            }
            
            var viewModel = new ActionKortingViewModel()
            {
                Korting = model,
                ActionType = actionType
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] 
        public async Task<IActionResult> Delete(ActionKortingViewModel model)
        {
            var alert = new Alert();// Alert    
            try
            {
                var originalModel = ApplicationDbContext.Kortingen.FirstOrDefault(m => m.Id == model.Korting.Id);
                if(originalModel == null)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.NOTEXISTS;
                    TempData["Status"] = ApplicationDbContextMessage.NOTEXISTS;
                    throw new Exception();
                }

                switch(model.ActionType)
                {
                    case ActionType.Delete:
                        alert.Message = ApplicationDbContextMessage.DELETEOK;
                        TempData["Status"] = ApplicationDbContextMessage.DELETEOK;
                        ApplicationDbContext.Entry(originalModel).State = EntityState.Deleted;
                        break;
                    case ActionType.SoftDelete:
                        alert.Message = ApplicationDbContextMessage.SOFTDELETEOK;
                        TempData["Status"] = ApplicationDbContextMessage.SOFTDELETEOK;
                        originalModel.DeletedAt = DateTime.Now;
                        ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                        break;
                    case ActionType.SoftUnDelete:
                        alert.Message = ApplicationDbContextMessage.SOFTUNDELETEOK;
                        TempData["Status"] = ApplicationDbContextMessage.SOFTUNDELETEOK;
                        originalModel.DeletedAt = (Nullable<DateTime>)null;
                        ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                        break;
                }

                
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {                   
                    switch(model.ActionType)
                    {
                        case ActionType.Delete:
                            TempData["Status"] = ApplicationDbContextMessage.DELETENOK;
                            break;
                        case ActionType.SoftDelete:
                            TempData["Status"] = ApplicationDbContextMessage.SOFTDELETENOK;
                            break;
                        case ActionType.SoftUnDelete:
                            TempData["Status"] = ApplicationDbContextMessage.SOFTUNDELETENOK;
                            break;
                    }
                    throw new Exception();
                } 

                if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(alert);
                }
                else
                {

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Korting/Create.cshtml
@model Accomo.Models.ViewModels.KortingViewModel
@{
    ViewBag.Title = "Korting aanmaken";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-cell--12-col-phone no-p-l">
    <div class="ahs-card-holder ahs-card-holder--first">
        <div class="mdl-card mdl-shadow--1dp ahs-card">
          <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Maak een nieuwe Korting aan</h2>
          </div>
          <div class="form-holder">
            <form asp-controller="Korting" asp-action="Create" method="post" asp-antiforgery="true">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <input class="mdl-textfield__input" asp-for="Korting.Naam">
                    <label class="mdl-textfield__label" asp-for="Korting.Naam">Naam</label>
                    <span class="mdl-textfield__error" asp-for="Korting.Naam" ></span>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <textarea class="mdl-textfield__input" rows="10" maxrows="20" asp-for="Korting.Beschrijving"> </textarea>
                    <label class="mdl-textfield__label" asp-for="Korting.Beschrijving">Beschrijving</label>
                    <span class="mdl-textfield__error" asp-for="Korting.Beschrijving"></span>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <input class="mdl-textfield__input" asp-for="Korting.Percentage">
                    <label class="mdl-textfield__label" asp-for="Korting.Percentage">Percentage korting</label>
                    <span class="mdl-textfield__error" asp-for="Korting.Percentage"></span>
                </div>
                <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">Opslaan</button>
            </form>
          </div>
        </div>
    </div>
</div>

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Korting/Delete.cshtml
@model Accomo.Models.ViewModels.ActionKortingViewModel
@{
    ViewBag.Title = "Kortingbeheer";
    ViewBag.SubTitle = @Model.Action;
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="mdl-cell mdl-cell--4-col">
    <div class="demo-card-wide mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">@Model.Action een bestaande Korting</h2>
    </div>
    <div class="mdl-card__supporting-text">
        Ben je zeker?
    </div>
    <div class="mdl-card__actions mdl-card--border">
        <form asp-controller="Korting" asp-action="Delete" method="post" asp-antiforgery="true">
            <input asp-for="Korting.Id" type="hidden">
            <input asp-for="Korting.Naam" type="hidden">
            <input asp-for="Korting.Beschrijving" type="hidden">
            <input asp-for="Korting.Percentage" type="hidden">
            <input asp-for="ActionType" type="hidden">
            <button type="submit" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">@Model.Action</button>
        </form>
    </div>
</div>

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Korting/Edit.cshtml
@model Accomo.Models.ViewModels.KortingViewModel
@{
    ViewBag.Title = "Kortingbeheer";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-cell--12-col-phone no-p-l">
    <div class="ahs-card-holder ahs-card-holder--first">
        <div class="mdl-card mdl-shadow--1dp ahs-card">
          <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Bewerk een Bed type</h2>
          </div>
          <div class="form-holder">
            <form asp-controller="Korting" asp-action="Edit" method="post" asp-antiforgery="true">
                <input asp-for="Korting.Id" type="hidden">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <input class="mdl-textfield__input" asp-for="Korting.Naam">
                    <label class="mdl-textfield__label" asp-for="Korting.Naam">Naam</label>
                    <span class="mdl-textfield__error" asp-for="Korting.Naam" ></span>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <textarea class="mdl-textfield__input" rows="10" maxrows="20" asp-for="Korting.Beschrijving"> </textarea>
                    <label class="mdl-textfield__label" asp-for="Korting.Beschrijving">Beschrijving</label>
                    <span class="mdl-textfield__error" asp-for="Korting.Beschrijving"></span>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <input class="mdl-textfield__input" asp-for="Korting.Percentage">
                    <label class="mdl-textfield__label" asp-for="Korting.Percentage">Percentage korting</label>
                    <span class="mdl-textfield__error" asp-for="Korting.Percentage"></span>
                </div>
                <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">Opslaan</button>
            </form>
          </div>
        </div>
    </div>
</div>

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Korting/Index.cshtml
@model ICollection<Accomo.Models.Korting>
@{
    ViewBag.Title = "Kortingenbeheer";
    ViewBag.SubTitle = "Beheer alle Kortingen vanaf hier.";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}

<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-cell--12-col-phone mdl-color--grey-100">
    @Html.Partial("_QuickActionsPartial")
</div>
@if (TempData["Status"] != null) {
<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-cell--12-col-phone mdl-color--grey-100">
    <span class="mdl-chip mdl-chip--contact">
        <i class="mdl-chip__contact mdl-color--teal mdl-color-text--white material-icons mdl-color-text--blue-600">info</i>
        <span class="mdl-chip__text">@TempData["Status"]</span>
    </span>
</div>
}
<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-cell--12-col-phone no-p-l">
   @Html.Partial("_ListPartial", @Model)
</div>

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Korting/_ListPartial.cshtml
@model ICollection<Accomo.Models.Korting>
@Html.AntiForgeryToken()
		@if (Model != null && Model.Count() > 0)
		{
      <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
        <thead>
            <tr>
            <th class="mdl-data-table__cell--non-numeric">
              <a asp-controller="Korting" asp-action="Index" asp-route-sortParam="@ViewBag.NameSortParam">
                Naam
              </a>
            </th>
            <th class="mdl-data-table__cell--non-numeric" >
                Beschrijving
            </th>
            <th class="mdl-data-table__cell--non-numeric" asp-route-sortParam="@ViewBag.PercentageSortParam">
                Percentage
            </th>
            <th class="mdl-data-table__cell--non-numeric">Actie</th>
            </tr>
        </thead>
        <tbody>
          @foreach (var korting in Model)
          {
            <tr>
            <td class="mdl-data-table__cell--non-numeric">@korting.Naam</td>
            <td class="mdl-data-table__cell--non-numeric mdl-data-table__cell--break">@korting.Beschrijving</td>
            <td class="mdl-data-table__cell--non-numeric mdl-data-table__cell--break">@korting.Percentage%</td>
            <td class="mdl-data-table__cell--non-numeric">
                <a asp-controller="Korting" asp-action="Edit" asp-route-id="@korting.Id">
                  <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">edit</i>
                </a>
                @if (@korting.DeletedAt != null)
                {
                    <a asp-controller="Korting" asp-action="Delete" asp-route-id="@korting.Id" asp-route-actionType="5" data-is-softdelete="true">
                      <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">delete</i>
                    </a>
                }
                else
                {
                    <a asp-controller="Korting" asp-action="Delete" asp-route-id="@korting.Id" asp-route-actionType="4">
                      <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">delete</i>
                    </a>
                }
                <a asp-controller="Korting" asp-action="Delete" asp-route-id="@korting.Id" asp-route-actionType="3">
                  <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">delete_forever</i>
                </a>
              </td>
            </tr>
          }
        </tbody>
    </table>
		}
		else
    {
        <p>Geen Kortingen in de database!</p>
    }
</div>

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Korting/_QuickActionsPartial.cshtml
<div class="ahs-list-overview">
    <div class=" mdl-color-text--blue-grey-400">
        <h3><i class=" material-icons f-left m-r-5">dvr</i> Overzicht</h3>
        <p>@ViewBag.Description</p>
        <ul class="ahs-list-overview__list">
            <li><a asp-controller="Korting" asp-action="Index"><i class="material-icons">list</i>Lijst van Kortingen</a></li>
            <li><a asp-controller="Korting" asp-action="Create"><i class="material-icons">add</i>Maak een nieuwe Korting</a></li>
        </ul>
    </div>
</div>