dotnet/src/Accomo.WWW/Areas/Backoffice/Controllers/BoekingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Accomo.Db;
using Accomo.Models;
using Accomo.Models.Security;
using Accomo.Models.Utilities;
using Accomo.Models.ViewModels;

namespace Accomo.WWW.Areas.Backoffice.Controllers 
{
    [Area("Backoffice")]
    public class BoekingController : BaseController 
    {
        public BoekingController(ApplicationDbContext applicationDbContext):base(applicationDbContext)
        {
        }

        public async Task<IActionResult> Index(string sortParam) {
            List<Boeking> boekingen = 
            await ApplicationDbContext.Boekingen
            .Include(o => o.Transacties)
            .Include(o => o.Accomodatie)
            .Include(o => o.User)
            .ToListAsync();

            // Sorting
            ViewBag.PrijsPerDagSortParam = "priceday_asc";
            ViewBag.PrijsPerVerblijfSortParam = "pricestay_asc";
            ViewBag.TotalSortParam = "total_asc";
            ViewBag.CheckInSortParam = "checkin_asc";
            ViewBag.CheckOutSortParam = "checkout_asc";
            ViewBag.GuestSortParam = "guestamount_asc";
            ViewBag.CancelSortParam = "canceldate_asc";
            ViewBag.AccomodatieSortParam = "accomodatie_asc";
            ViewBag.UserSortParam = "username_asc";
            ViewBag.CreatedAtSortParam = "createdat_asc";

            

            if(String.IsNullOrEmpty(sortParam))
            {
                boekingen = boekingen.OrderBy(o => o.CreatedAt).ToList();
            }
            else
            {
                switch(sortParam)
                {
                    case "priceday_asc":
                        ViewBag.PrijsPerDagSortParam = "priceday_desc";
                        boekingen = boekingen.OrderBy(o => o.PrijsPerDag).ToList();
                        break;
                    case "priceday_desc":
                        ViewBag.PrijsPerDagSortParam = "priceday_asc";
                        boekingen = boekingen.OrderByDescending(o => o.PrijsPerDag).ToList();
                        break; 
                    case "pricestay_asc":
                        ViewBag.PrijsPerVerblijfSortParam = "pricestay_desc";
                        boekingen = boekingen.OrderBy(o => o.PrijsPerVerblijf).ToList();
                        break;
                    case "pricestay_desc":
                        ViewBag.PrijsPerVerblijfSortParam = "pricestay_asc";
                        boekingen = boekingen.OrderByDescending(o => o.PrijsPerVerblijf).ToList();
                        break;    
                    case "total_asc":
                        ViewBag.TotalSortParam = "total_desc";
                        boekingen = boekingen.OrderBy(o => o.TotaalBedrag).ToList();
                        break;    
                    case "total_desc":
                        ViewBag.TotalSortParam = "total_asc";
                        boekingen = boekingen.OrderByDescending(o => o.TotaalBedrag).ToList();
                        break;    
                    case "checkin_asc":
                        ViewBag.CheckInSortParam = "checkin_desc";
                        boekingen = boekingen.OrderByDescending(o => o.CheckIn).ToList();
                        break;    
                    case "checkin_desc":
                        ViewBag.CheckInSortParam = "checkin_asc";
                        boekingen = boekingen.OrderBy(o => o.CheckIn).ToList();
                        break;    
                    case "checkout_asc":
                        ViewBag.CheckOutSortParam = "checkout_desc";
                        boekingen = boekingen.OrderByDescending(o => o.CheckOut).ToList();
                        break;    
                    case "checkout_desc":
                        ViewBag.CheckOutSortParam = "checkout_asc";
                        boekingen = boekingen.OrderBy(o => o.CheckOut).ToList();
                        break;    
                    case "guestamount_asc":
                        ViewBag.GuestSortParam = "guestamount_desc";
                        boekingen = boekingen.OrderBy(o => o.AantalGasten).ToList();
                        break;    
                    case "guestamount_desc":
                        ViewBag.GuestSortParam = "guestamount_asc";
                        boekingen = boekingen.OrderByDescending(o => o.AantalGasten).ToList();
                        break;     
                    case "canceldate_asc":
                        ViewBag.CancelSortParam = "canceldate_desc";
                        boekingen = boekingen.OrderBy(o => o.AnnuleringsDatum).ToList();
                        break;    
                    case "canceldate_desc":
                        ViewBag.CancelSortParam = "canceldate_asc";
                        boekingen = boekingen.OrderByDescending(o => o.AnnuleringsDatum).ToList();
                        break;     
                    case "accomodatie_asc":
                        ViewBag.AccomodatieSortParam = "accomodatie_desc";
                        boekingen = boekingen.OrderBy(o => o.Accomodatie.Naam).ToList();
                        break;    
                    case "accomodatie_desc":
                        ViewBag.AccomodatieSortParam = "accomodatie_asc";
                        boekingen = boekingen.OrderByDescending(o => o.Accomodatie.Naam).ToList();
                        break;      
                    case "username_asc":
                        ViewBag.UserSortParam = "username_desc";
                        boekingen = boekingen.OrderBy(o => o.User.FirstName).ThenBy(o => o.User.LastName).ToList();
                        break;    
                    case "username_desc":
                        ViewBag.UserSortParam = "username_asc";
                        boekingen = boekingen.OrderByDescending(o => o.User.FirstName).ThenByDescending(o => o.User.LastName).ToList();
                        break;      
                    case "createdat_asc":
                        ViewBag.CreatedAtSortParam = "createdat_desc";
                        boekingen = boekingen.OrderBy(o => o.CreatedAt).ToList();
                        break;    
                    case "createdat_desc":
                        ViewBag.CreatedAtSortParam = "createdat_asc";
                        boekingen = boekingen.OrderByDescending(o => o.CreatedAt).ToList();
                        break;                    
                }
            }
            if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest") 
            {
                return PartialView("_ListPartial", boekingen);
            }
            
            return View(boekingen);
        }
        
        
        [HttpGet]
        public async Task<IActionResult> Edit(Int16? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            
            var model = await ApplicationDbContext.Boekingen.FirstOrDefaultAsync(m => m.Id == id);
            
            if(model == null)
            {
                return RedirectToAction("Index");
            }

            var viewModel = await ViewModel(model);
            
            return View(viewModel);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BoekingViewModel model)
        {
            var alert = new Alert();
            try 
            {
                if(!ModelState.IsValid)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.INVALID;
                    TempData["Status"] = ApplicationDbContextMessage.INVALID;
                    throw new Exception();
                }   
                    
                var originalModel = ApplicationDbContext.Boekingen.FirstOrDefault(m => m.Id == model.Boeking.Id);
                
                if(originalModel == null) 
                {
                    TempData["Status"] = ApplicationDbContextMessage.NOTEXISTS;
                    throw new Exception();
                }

                originalModel.CheckIn = model.Boeking.CheckIn;
                originalModel.CheckOut = model.Boeking.CheckOut;
                originalModel.AantalGasten = model.Boeking.AantalGasten;
                originalModel.TotaalBedrag = model.Boeking.TotaalBedrag;
                
                ApplicationDbContext.Attach(originalModel);
                ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {
                    TempData["Status"] = ApplicationDbContextMessage.EDITNOK;
                    throw new Exception();
                } 
                
                alert.Message = ApplicationDbContextMessage.EDITOK;
                TempData["Status"] = "Boeking met Id: " + model.Boeking.Id + " is succesvol bewerkt.";

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;
                TempData["Status"] = ex.Message;

                model = await ViewModel(model.Boeking);
                ModelState.AddModelError(string.Empty, alert.ExceptionMessage);
            }
            return View(model);
        }
        
        [HttpGet("[area]/[controller]/[action]/{id:int}")]
        public async Task<IActionResult> Delete(Int16 id, [FromQuery] ActionType actionType)
        {
            var model = await ApplicationDbContext.Boekingen.FirstOrDefaultAsync(m => m.Id == id);
            if(model == null)
            {
                return RedirectToAction("Index");
            }
            

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Boeking/Create.cshtml
@model Accomo.Models.ViewModels.BedTypeViewModel
@{
    ViewBag.Title = "Bedtype aanmaken";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-cell--12-col-phone no-p-l">
    <div class="ahs-card-holder ahs-card-holder--first">
        <div class="mdl-card mdl-shadow--1dp ahs-card">
          <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Maak een nieuw bedtype aan</h2>
          </div>
          <div class="form-holder">
            <form asp-controller="BedType" asp-action="Create" method="post" asp-antiforgery="true">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <input class="mdl-textfield__input" asp-for="BedType.Naam">
                    <label class="mdl-textfield__label" asp-for="BedType.Naam">Naam</label>
                    <span class="mdl-textfield__error" asp-for="BedType.Naam" ></span>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <textarea class="mdl-textfield__input" rows="10" maxrows="20" asp-for="BedType.Beschrijving"> </textarea>
                    <label class="mdl-textfield__label" asp-for="BedType.Beschrijving">Beschrijving</label>
                    <span class="mdl-textfield__error" asp-for="BedType.Beschrijving"></span>
                </div>
                <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">Opslaan</button>
            </form>
          </div>
        </div>
    </div>
</div>

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Boeking/Delete.cshtml
@model Accomo.Models.ViewModels.ActionBoekingViewModel
@{
    ViewBag.Title = "Boekingbeheer";
    ViewBag.SubTitle = @Model.Action;
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="mdl-cell mdl-cell--4-col">
    <div class="demo-card-wide mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">@Model.Action een bestaand Boeking</h2>
    </div>
    <div class="mdl-card__supporting-text">
        Ben je zeker?
    </div>
    <div class="mdl-card__actions mdl-card--border">
        <form asp-controller="Boeking" asp-action="Delete" method="post" asp-antiforgery="true">
            <input asp-for="Boeking.Id" type="hidden">
            <input asp-for="ActionType" type="hidden">
            <button type="submit" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">@Model.Action</button>
        </form>
    </div>
</div>

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Boeking/Edit.cshtml
@model Accomo.Models.ViewModels.BoekingViewModel
@{
    ViewBag.Title = "Boeking beheer";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-cell--12-col-phone no-p-l">
    <div class="ahs-card-holder ahs-card-holder--first">
        <div class="mdl-card mdl-shadow--1dp ahs-card">
          <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Bewerk een boeking</h2>
          </div>
          <div class="form-holder">
            <form asp-controller="Boeking" asp-action="Edit" method="post" asp-antiforgery="true">
                <input asp-for="Boeking.Id" type="hidden">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <input class="mdl-textfield__input" asp-for="Boeking.CheckIn">
                    <label class="mdl-textfield__label" asp-for="Boeking.CheckIn">Check-In Datum</label>
                    <span class="mdl-textfield__error" asp-for="Boeking.CheckIn" ></span>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <input class="mdl-textfield__input" asp-for="Boeking.CheckOut">
                    <label class="mdl-textfield__label" asp-for="Boeking.CheckOut">Check-Out Datum</label>
                    <span class="mdl-textfield__error" asp-for="Boeking.CheckOut" ></span>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <input class="mdl-textfield__input" asp-for="Boeking.AantalGasten">
                    <label class="mdl-textfield__label" asp-for="Boeking.AantalGasten">Aantal Gasten</label>
                    <span class="mdl-textfield__error" asp-for="Boeking.AantalGasten" ></span>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ahs-textfield--block">
                    <input class="mdl-textfield__input" asp-for="Boeking.TotaalBedrag">
                    <label class="mdl-textfield__label" asp-for="Boeking.TotaalBedrag">Totaalbedrag</label>
                    <span class="mdl-textfield__error" asp-for="Boeking.TotaalBedrag" ></span>
                </div>
                <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">Opslaan</button>
            </form>
          </div>
        </div>
    </div>
</div>

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Boeking/Index.cshtml
@model ICollection<Accomo.Models.Boeking>
@{
    ViewBag.Title = "Boeking-beheer";
    ViewBag.SubTitle = "Beheer alle Boekingen vanaf hier.";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}

<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-cell--12-col-phone mdl-color--grey-100">
    @Html.Partial("_QuickActionsPartial")
</div>
@if (TempData["Status"] != null) {
<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-cell--12-col-phone mdl-color--grey-100">
    <span class="mdl-chip mdl-chip--contact">
        <i class="mdl-chip__contact mdl-color--teal mdl-color-text--white material-icons mdl-color-text--blue-600">info</i>
        <span class="mdl-chip__text">@TempData["Status"]</span>
    </span>
</div>
}
<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-cell--12-col-phone no-p-l">
   @Html.Partial("_ListPartial", @Model)
</div>

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Boeking/_ListPartial.cshtml
@model ICollection<Accomo.Models.Boeking>
@Html.AntiForgeryToken()
		@if (Model != null && Model.Count() > 0)
		{
      <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
        <thead>
            <tr>
            <th class="mdl-data-table__cell--non-numeric">
              <a asp-controller="Boeking" asp-action="Index" asp-route-sortParam="@ViewBag.AccomodatieSortParam">
                Accomodatie
              </a>
            </th>
            <th class="mdl-data-table__cell--non-numeric">
              <a asp-controller="Boeking" asp-action="Index" asp-route-sortParam="@ViewBag.CheckInSortParam">
                Check-In
              </a>
            </th>
            <th class="mdl-data-table__cell--non-numeric">
              <a asp-controller="Boeking" asp-action="Index" asp-route-sortParam="@ViewBag.CheckOutSortParam">
                Check-Out
              </a>
            </th>
            <th class="mdl-data-table__cell--numeric">
              <a asp-controller="Boeking" asp-action="Index" asp-route-sortParam="@ViewBag.GuestSortParam">
                Aantal Gasten
              </a>
            </th>
            <th class="mdl-data-table__cell--numeric">
              <a asp-controller="Boeking" asp-action="Index" asp-route-sortParam="@ViewBag.PrijsPerDagSortParam">
                Prijs per dag
              </a>
            </th>
            <th class="mdl-data-table__cell--numeric">
              <a asp-controller="Boeking" asp-action="Index" asp-route-sortParam="@ViewBag.PrijsPerVerblijfSortParam">
                Prijs per verblijf
              </a>
            </th>
            <th class="mdl-data-table__cell--numeric">
              <a asp-controller="Boeking" asp-action="Index" asp-route-sortParam="@ViewBag.TotalSortParam">
                Totaalbedrag
              </a>
            </th>
            <th class="mdl-data-table__cell--non-numeric">
              <a asp-controller="Boeking" asp-action="Index" asp-route-sortParam="@ViewBag.UserSortParam">
                Gast
              </a>
            </th>
            <th class="mdl-data-table__cell--non-numeric">
              <a asp-controller="Boeking" asp-action="Index" asp-route-sortParam="@ViewBag.CreatedAtSortParam">
                Gereserveerd op
              </a>
            </th>
            <th class="mdl-data-table__cell--non-numeric">Actie</th>
            </tr>
        </thead>
        <tbody>
          @foreach (var boeking in Model)
          {
            <tr>
            <td class="mdl-data-table__cell--non-numeric">@boeking.Accomodatie.Naam</td>
            <td class="mdl-data-table__cell--non-numeric">@boeking.CheckIn</td>
            <td class="mdl-data-table__cell--non-numeric">@boeking.CheckOut</td>
            <td class="mdl-data-table__cell--numeric">@boeking.AantalGasten</td>
            <td class="mdl-data-table__cell--numeric">@boeking.PrijsPerDag</td>
            <td class="mdl-data-table__cell--numeric">@boeking.PrijsPerVerblijf</td>
            <td class="mdl-data-table__cell--numeric">@boeking.TotaalBedrag</td>
            <td class="mdl-data-table__cell--non-numeric">@boeking.User.FirstName @boeking.User.LastName</td>
            <td class="mdl-data-table__cell--non-numeric">@boeking.CreatedAt</td>
            <td class="mdl-data-table__cell--non-numeric">
                <a asp-controller="Boeking" asp-action="Edit" asp-route-id="@boeking.Id">
                  <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">edit</i>
                </a>
                @if (@boeking.DeletedAt != null)
                {
                    <a asp-controller="Boeking" asp-action="Delete" asp-route-id="@boeking.Id" asp-route-actionType="5" data-is-softdelete="true">
                      <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">delete</i>
                    </a>
                }
                else
                {
                    <a asp-controller="Boeking" asp-action="Delete" asp-route-id="@boeking.Id" asp-route-actionType="4">
                      <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">delete</i>
                    </a>
                }
                <a asp-controller="Boeking" asp-action="Delete" asp-route-id="@boeking.Id" asp-route-actionType="3">
                  <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">delete_forever</i>
                </a>
              </td>
            </tr>
          }
        </tbody>
    </table>
		}
		else
    {
        <p>Geen Boekingen in de database!</p>
    }
</div>

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Boeking/_QuickActionsPartial.cshtml
<div class="ahs-list-overview">
    <div class=" mdl-color-text--blue-grey-400">
        <h3><i class=" material-icons f-left m-r-5">dvr</i> Overzicht</h3>
        <p>@ViewBag.Description</p>
        <ul class="ahs-list-overview__list">
            <li><a asp-controller="Boeking" asp-action="Index"><i class="material-icons">list</i>Lijst van Boekingen</a></li>
        </ul>
    </div>
</div>