dotnet/src/Accomo.WWW/Areas/Backoffice/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Accomo.Db;
using Accomo.Models;
using Accomo.Models.Security;
using Accomo.Models.Utilities;
using Accomo.Models.ViewModels;

namespace Accomo.WWW.Areas.Backoffice.Controllers 
{
    [Area("Backoffice")]
    public class RoleController  : Controller
    {   
        public  UserManager<ApplicationUser> _userManager;
        public  RoleManager<ApplicationRole> _roleManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        public ApplicationDbContext _applicationdbContext;
        public RoleController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            RoleManager<ApplicationRole> roleManager,
            ApplicationDbContext applicationdbContext)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _applicationdbContext = applicationdbContext;

        }

        public async Task<IActionResult> Index(string sortParam) {
            List<ApplicationRole> roles = 
            await _roleManager.Roles.ToListAsync();

            // Sorting
            ViewBag.NameSortParam = "name_asc";


            if(String.IsNullOrEmpty(sortParam))
            {
                roles = roles.OrderBy(o => o.Name).ToList();
            }
            else
            {
                switch(sortParam)
                {
                    case "name_asc":
                        ViewBag.NameSortParam = "name_desc";
                        roles = roles.OrderBy(o => o.Name).ToList();
                        break;
                    case "name_desc":
                        ViewBag.NameSortParam = "name_asc";
                        roles = roles.OrderByDescending(o => o.Name).ToList();
                        break;                    
                }
            }
            if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest") 
            {
                return PartialView("_ListPartial", roles);
            }
            
            return View(roles);
        }
        
        [HttpGet]
        public async Task<IActionResult> Create() 
        {  
            var viewModel = await ViewModel();
            
            return View(viewModel);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            var alert = new Alert();
            if (ModelState.IsValid)
            {
                try{
                    var role = new ApplicationRole{ Name = model.ApplicationRole.Name, Beschrijving = model.ApplicationRole.Beschrijving};
                    var result = await _roleManager.CreateAsync(role);
                    if (result.Succeeded)
                    {
                    TempData["Status"] = "Role met naam: " + model.ApplicationRole.Name + " is succesvol aangemaakt.";
                    }
                    return RedirectToAction("Index");
                }catch(Exception ex)
            {
               
                TempData["Status"] = ex.Message;
                                
                return View(model);

            }
                

            }
            return View(model);
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            
            var model = await _roleManager.FindByIdAsync(id);         
            if(model == null)
            {
                TempData["Status"] = "Er is geen gelijknamige record gevonden.";
                return RedirectToAction("Index");
            }

            var viewModel = await ViewModel(model);
            
            return View(viewModel);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RoleViewModel model)
        {
            var alert = new Alert();
            try 
            {
                if(!ModelState.IsValid)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.INVALID;
                    TempData["Status"] = ApplicationDbContextMessage.INVALID;
                    throw new Exception();
                }   
                    
                var originalModel = _roleManager.Roles.FirstOrDefault(m => m.Id == model.ApplicationRole.Id);
                
                if(originalModel == null) 
                {
                    TempData["Status"] = ApplicationDbContextMessage.NOTEXISTS;
                    throw new Exception();
                }

                originalModel.Name = model.ApplicationRole.Name;
                originalModel.Beschrijving = model.ApplicationRole.Beschrijving;


                var result = await _roleManager.UpdateAsync(originalModel);
                if (result.Succeeded)
                    {
                    TempData["Status"] = "Role met naam: " + model.ApplicationRole.Name + " is succesvol bewerkt.";
                    }
                    return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;
                TempData["Status"] = ex.Message;

                model = await ViewModel(model.ApplicationRole);
                ModelState.AddModelError(string.Empty, alert.ExceptionMessage);
            }
            return View(model);
        }
        
        //[HttpGet("[area]/[controller]/[action]/{id:int}")]
        [HttpGet]
        public async Task<IActionResult> Delete(string id, [FromQuery] ActionType actionType)
        {
            var model = await _roleManager.FindByIdAsync(id);  
            Console.WriteLine("Naam van de role: " + id);
            //var newId = new Guid(id);
            //var model = await _applicationdbContext.ApplicationRoles.FirstOrDefaultAsync(o => o.Name == roleName);
            if(model == null)
            {
                Console.WriteLine("BROLLLL");
                return RedirectToAction("Index");
            }
            
            var viewModel = new ActionRoleViewModel()
            {
                ApplicationRole = model,
                ActionType = actionType
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ActionRoleViewModel model)
        {
            var alert = new Alert();// Alert    
            try
            {
                var originalModel = _roleManager.Roles.FirstOrDefault(m => m.Id == model.ApplicationRole.Id);
                if(originalModel == null)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.NOTEXISTS;
                    TempData["Status"] = ApplicationDbContextMessage.NOTEXISTS;
                    throw new Exception();
                }
                try{

                
                    switch(model.ActionType)
                    {
                        case ActionType.Delete:
                            alert.Message = ApplicationDbContextMessage.DELETEOK;
                            TempData["Status"] = ApplicationDbContextMessage.DELETEOK;
                            await _roleManager.DeleteAsync(originalModel);
                            break;
                        case ActionType.SoftDelete:
                            alert.Message = ApplicationDbContextMessage.SOFTDELETEOK;
                            TempData["Status"] = ApplicationDbContextMessage.SOFTDELETEOK;
                            originalModel.DeletedAt = DateTime.Now;
                            await _roleManager.UpdateAsync(originalModel);
                            break;
                        case ActionType.SoftUnDelete:
                            alert.Message = ApplicationDbContextMessage.SOFTUNDELETEOK;
                            TempData["Status"] = ApplicationDbContextMessage.SOFTUNDELETEOK;
                            originalModel.DeletedAt = (Nullable<DateTime>)null;
                            await _roleManager.UpdateAsync(originalModel);
                            break;
                    }
                }catch(Exception ex)
                {
                        switch(model.ActionType)
                    {
                        case ActionType.Delete:
                            TempData["Status"] = ApplicationDbContextMessage.DELETENOK;
                            break;
                        case ActionType.SoftDelete:
                            TempData["Status"] = ApplicationDbContextMessage.SOFTDELETENOK;
                            break;
                        case ActionType.SoftUnDelete:
                            TempData["Status"] = ApplicationDbContextMessage.SOFTUNDELETENOK;
                            break;
                    }

                }
                
                    
                if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(alert);
                }
                else
                {
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;

                if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(alert);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
        }
        

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Shared/_Authorization.cshtml
<!doctype html>
<!-- [if lt IE 7]><html dir="ltr" lang="nl-be" class="no-js lt-ie7"><![endif]-->
<!-- [if lt IE 8]><html dir="ltr" lang="nl-be" class="no-js lt-ie8"><![endif]-->
<!-- [if lt IE 9]><html dir="ltr" lang="nl-be" class="no-js lt-ie9"><![endif]-->
<!-- [if lt IE 10]><html dir="ltr" lang="nl-be" class="no-js lt-ie10"><![endif]-->
<!-- [if (gt IE 9)|!(IE)]><!-->
<html dir="ltr" lang="nl-be" class="no-js mdl-js" prefix="og: http://ogp.me/ns#">
<!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title Accomo - Voel je thuis</title>
    <meta name="description" content="@ViewBag.Description">
    <meta name="keywords" content="@ViewBag.Keywords">
    <meta name="author" content="@ViewBag.Author">
    <meta name="copyright" content="Copyright 2003-16 Arteveldehogeschool. Alle rechten voorbehouden.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="images/android-desktop.png">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Material Design Lite">
    <link rel="apple-touch-icon-precomposed" href="images/ios-desktop.png">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">

    <link rel="shortcut icon" href="images/favicon.png">

    <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
    <!--
    <link rel="canonical" href="http://www.example.com/">
    -->

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet"  href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" >

    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css">
    <link rel="stylesheet" href="~/css/backoffice.css" />
    @RenderSection("styles", required: false)
    <style>
    #view-source {
      position: fixed;
      display: block;
      right: 0;
      bottom: 0;
      margin-right: 40px;
      margin-bottom: 40px;
      z-index: 900;
    }
    .mdl-layout {
	align-items: center;
  justify-content: center;
}
.mdl-layout__content {
	padding: 24px;
	flex: none;
}
    </style>
  </head>
  <body>
      <div class="mdl-layout mdl-js-layout mdl-color--grey-100">
            <main class="mdl-layout__content">
                <div class="mdl-card mdl-shadow--6dp">
                    <div class="mdl-card__title mdl-color--indigo-500 mdl-color-text--white">
                        <h2 class="mdl-card__title-text">@ViewBag.Title</h2>
                    </div>
                <div class="mdl-card__supporting-text">
                        @* Render the body of the view *@
                        @RenderBody()
                    </div>
                </div>
            </main>
        </div>
         @* Modal Popup Partial *@
    @Html.Partial("_Modal")

    @* Bottom Scripts *@
    <script src="https://code.getmdl.io/1.2.1/material.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="~/js/backoffice/main.js"></script>
    @* Custom scripts specified in the views*@
    @RenderSection("scripts", required: false)
  </body>
   
    
</html>
  

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Shared/_Header.cshtml
<header class="demo-header mdl-layout__header mdl-color--grey-100 mdl-color-text--grey-600 ahs-header">
  <div class="mdl-layout__header-row ahs-header__row">
    <span class="mdl-layout-title ahs-header__row__title">Accomo Backoffice</span>
    <div class="mdl-layout-spacer"></div>
  </div>
</header>

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Shared/_Layout.cshtml
<!doctype html>
<!-- [if lt IE 7]><html dir="ltr" lang="nl-be" class="no-js lt-ie7"><![endif]-->
<!-- [if lt IE 8]><html dir="ltr" lang="nl-be" class="no-js lt-ie8"><![endif]-->
<!-- [if lt IE 9]><html dir="ltr" lang="nl-be" class="no-js lt-ie9"><![endif]-->
<!-- [if lt IE 10]><html dir="ltr" lang="nl-be" class="no-js lt-ie10"><![endif]-->
<!-- [if (gt IE 9)|!(IE)]><!-->
<html dir="ltr" lang="nl-be" class="no-js mdl-js" prefix="og: http://ogp.me/ns#">
<!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title Accomo - Voel je thuis</title>
    <meta name="description" content="@ViewBag.Description">
    <meta name="keywords" content="@ViewBag.Keywords">
    <meta name="author" content="@ViewBag.Author">
    <meta name="copyright" content="Copyright 2003-16 Arteveldehogeschool. Alle rechten voorbehouden.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="images/android-desktop.png">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Material Design Lite">
    <link rel="apple-touch-icon-precomposed" href="images/ios-desktop.png">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">

    <link rel="shortcut icon" href="images/favicon.png">

    <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
    <!--
    <link rel="canonical" href="http://www.example.com/">
    -->

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet"  href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" >

    <link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.cyan-light_blue.min.css">
    <link rel="stylesheet" href="~/css/backoffice.css" />
    @RenderSection("styles", required: false)
    <style>
    #view-source {
      position: fixed;
      display: block;
      right: 0;
      bottom: 0;
      margin-right: 40px;
      margin-bottom: 40px;
      z-index: 900;
    }
    </style>
  </head>
  <body>
    <div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">

      @* Header Partial *@
      @Html.Partial("_Header")

      @* Sidebar Partial *@
      @Html.Partial("_Sidebar")

      @* Main Content *@
      <main class="mdl-layout__content mdl-color--grey-100 page">
        <section>
          <div class="mdl-color--grey-300 ahs-main-header relative clear">
            <h3 class="mdl-color-text--white m-t-20 m-b-5">@ViewBag.Title</h3>
            <h4 class="mdl-color-text--white m-b-20 no-m-t w100">@ViewBag.SubTitle</h4>
          </div>
          <div class="mdl-grid">
            @* Render the body of the view *@
            @RenderBody()
          </div>
        </section>
      </main>
    </div>

    @* Modal Popup Partial *@
    @Html.Partial("_Modal")

    @* Bottom Scripts *@
    <script src="https://code.getmdl.io/1.2.1/material.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="~/js/backoffice/main.js"></script>
    @* Custom scripts specified in the views*@
    @RenderSection("scripts", required: false)
    
  </body>
</html>

dotnet/src/Accomo.WWW/Areas/Backoffice/Views/Shared/_Sidebar.cshtml
@using Microsoft.AspNetCore.Identity
@using Accomo.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<div class="mdl-layout__drawer mdl-color-text--blue-grey-50 ahs-sidebar">
  <header class="mdl-color--blue-grey-800 ahs-sidebar__header">
    <div class="demo-avatar-dropdown">
      <div class="ahs-sidebar__header__user" style="background-image: url('../images/user.png')"> 
      </div>
      <span>@UserManager.GetUserName(User)</span>
      <div class="mdl-layout-spacer"></div>
      <button id="accbtn" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
        <i class="material-icons" role="presentation">arrow_drop_down</i>
        <span class="visuallyhidden">Accounts</span>
      </button>
      <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="accbtn">
        <form asp-controller="Account" asp-action="LogOff" method="post" id="logoutForm">
                <li class="mdl-menu__item"><button type="submit" class="logoutbtn">Log off</button></li>
        </form>
      </ul>
    </div>
  </header>
  <nav class="mdl-navigation ahs-sidebar__navigation">
    <ul class="demo-list-icon mdl-list">
      <li class="mdl-list__item ahs-sidebar__navigation_list__item mdl-color-text--blue-grey-600 ahs-sidebar__navigation_list__item__active">
          <span class="mdl-list__item-primary-content">
            <a asp-controller="Home" asp-action="Index">
            <i class="material-icons mdl-list__item-icon mdl-color-text--blue-grey-600 ">home</i> 
            <span class="list__item__title">Home</span>
            </a>
          </span>
      </li>
      <li class="mdl-list__item ahs-sidebar__navigation_list__item mdl-color-text--blue-grey-600 navigation__toggle__item">
        <div class="mdl-list__item-primary-content">   
            <i class="material-icons mdl-list__item-icon mdl-color-text--blue-grey-600 ">domain</i> 
            <span class="list__item__title">Accomo</span>
            <i class="material-icons mdl-color-text--blue-grey-800 arrow_drop_down" role="presentation">arrow_drop_down</i>
        </div>
        <ul class="ahs-sidebar__navigation__submenu">
          <li><a class="mdl-navigation__link mdl-color-text--blue-grey-800" asp-controller="Accomodatie" asp-action="Index"><i class="mdl-color-text--blue-grey-800 material-icons" role="presentation">store_mall_directory</i>Accomodaties</a></li>
          <li><a class="mdl-navigation__link mdl-color-text--blue-grey-800" asp-controller="AccomodatieLocatie" asp-action="Index"><i class="mdl-color-text--blue-grey-800 material-icons" role="presentation">map</i>Locaties</a></li>
          <li><a class="mdl-navigation__link mdl-color-text--blue-grey-800" asp-controller="Categorie" asp-action="Index"><i class="mdl-color-text--blue-grey-800 material-icons" role="presentation">label</i>Categorieën</a></li>
          <li><a class="mdl-navigation__link mdl-color-text--blue-grey-800" asp-controller="Review" asp-action="Index"><i class="mdl-color-text--blue-grey-800 material-icons" role="presentation">book</i>Reviews</a></li>
        </ul>
      </li>
      <li class="mdl-list__item ahs-sidebar__navigation_list__item mdl-color-text--blue-grey-600 navigation__toggle__item">
        <div class="mdl-list__item-primary-content">   
            <i class="material-icons mdl-list__item-icon mdl-color-text--blue-grey-600 ">compare_arrows</i> 
            <span class="list__item__title">Transacties</span>
            <i class="material-icons mdl-color-text--blue-grey-800 arrow_drop_down" role="presentation">arrow_drop_down</i>
        </div>
        <ul class="ahs-sidebar__navigation__submenu">
          <li><a class="mdl-navigation__link mdl-color-text--blue-grey-800" asp-controller="Transactie" asp-action="Index"><i class="mdl-color-text--blue-grey-800 material-icons" role="presentation">description</i>Transacties</a></li>
          <li><a class="mdl-navigation__link mdl-color-text--blue-grey-800" asp-controller="Korting" asp-action="Index"><i class="mdl-color-text--blue-grey-800 material-icons" role="presentation">euro_symbol</i>Kortingen</a></li>
          <li><a class="mdl-navigation__link mdl-color-text--blue-grey-800" asp-controller="Boeking" asp-action="Index"><i class="mdl-color-text--blue-grey-800 material-icons" role="presentation">book</i>Boekingen</a></li>
        </ul>
      </li>
      <li class="mdl-list__item ahs-sidebar__navigation_list__item mdl-color-text--blue-grey-600 navigation__toggle__item">
        <div class="mdl-list__item-primary-content">   
            <i class="material-icons mdl-list__item-icon mdl-color-text--blue-grey-600 ">list</i> 
            <span class="list__item__title">Lijsten</span>
            <i class="material-icons mdl-color-text--blue-grey-800 arrow_drop_down" role="presentation">arrow_drop_down</i>
        </div>
        <ul class="ahs-sidebar__navigation__submenu">
          <li><a class="mdl-navigation__link mdl-color-text--blue-grey-800" asp-controller="AccomodatieType" asp-action="Index"><i class="mdl-color-text--blue-grey-800 material-icons" role="presentation">book</i>Accomodatietypes</a></li>
          <li><a class="mdl-navigation__link mdl-color-text--blue-grey-800" asp-controller="BedType" asp-action="Index"><i class="mdl-color-text--blue-grey-800 material-icons" role="presentation">description</i>Bedtypes</a></li>
          <li><a class="mdl-navigation__link mdl-color-text--blue-grey-800" asp-controller="VoorzieningType" asp-action="Index"><i class="mdl-color-text--blue-grey-800 material-icons" role="presentation">book</i>Voorzieningen</a></li>
          <li><a class="mdl-navigation__link mdl-color-text--blue-grey-800" asp-controller="Veiligheidsvoorziening" asp-action="Index"><i class="mdl-color-text--blue-grey-800 material-icons" role="presentation">book</i>Veiligheidsvoorzieningen</a></li>
          <li><a class="mdl-navigation__link mdl-color-text--blue-grey-800" asp-controller="Huisregel" asp-action="Index"><i class="mdl-color-text--blue-grey-800 material-icons" role="presentation">book</i>Huisregels</a></li>
          <li><a class="mdl-navigation__link mdl-color-text--blue-grey-800" asp-controller="MediaType" asp-action="Index"><i class="mdl-color-text--blue-grey-800 material-icons" role="presentation">perm_media</i>Mediatypes</a></li>
        </ul>
      </li>
      <li class="mdl-list__item ahs-sidebar__navigation_list__item  mdl-color-text--blue-grey-600 navigation__toggle__item">
        <div class="mdl-list__item-primary-content">   
            <i class="material-icons mdl-list__item-icon mdl-color-text--blue-grey-600 ">perm_identity</i> 
            <span class="list__item__title">User</span>
            <i class="material-icons mdl-color-text--blue-grey-800 arrow_drop_down" role="presentation">arrow_drop_down</i>
        </div>
        <ul class="ahs-sidebar__navigation__submenu">
           <li><a class="mdl-navigation__link mdl-color-text--blue-grey-800" asp-controller="User" asp-action="Index"><i class="mdl-color-text--blue-grey-800 material-icons" role="presentation">account_box</i>Users</a></li>
      <li><a class="mdl-navigation__link mdl-color-text--blue-grey-800" asp-controller="Role" asp-action="Index"><i class="mdl-color-text--blue-grey-800 material-icons" role="presentation">security</i>Roles</a></li>
        </ul>
      </li>
      
    </ul>
  </nav>
</div>